# Generated by Django 3.1.5 on 2021-01-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
